DROP TABLE  IF EXISTS ENTRENADORES;
CREATE TABLE ENTRENADORES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL);
INSERT INTO ENTRENADORES (NOMBRE) VALUES ('JUAN');
INSERT INTO ENTRENADORES (NOMBRE) VALUES ('PEDRO');