DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO INT NOT NULL,
    LOCALIDAD VARCHAR(100) NOT NULL,
    PROVINCIA VARCHAR(100) NOT NULL);

DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    APELLIDO VARCHAR(100) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    MATRICULA VARCHAR(100) NOT NULL);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    APELLIDO VARCHAR(100) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DNI INT NOT NULL,
    FECHA DATE NOT NULL,
    DOMICILIO_ID INT NOT NULL);



INSERT INTO DOMICILIOS(CALLE, NUMERO, LOCALIDAD, PROVINCIA)
VALUES('Amenabar', 832, 'CABA', 'BsAs');

INSERT INTO ODONTOLOGOS(APELLIDO, NOMBRE, MATRICULA)
VALUES('Muelas', 'Juan', 'MP123');

INSERT INTO PACIENTES (APELLIDO, NOMBRE,  EMAIL, DNI, FECHA, DOMICILIO_ID)
VALUES('Huertas', 'Alejandro',  'alejo29h@gmail.com', 95198668, '2023-10-21', 1 );